### ISSUE TITLE
Blog is unable to render tables in correct format

### ISSUE THREAD

**Issue by SankBad** [operate-first/operate-first.github.io-old#40] opened 2020-10-15 14:33 UTC
I am trying to publish a blog. I made all the suggested changes in my fork repository. 
I build the site locally for testing purposes and found out that table is not rendered. 

Fork repo: [Link](https://github.com/SankBad/operate-first.github.io)

Blog markdown format: [Link](https://github.com/SankBad/operate-first.github.io/blob/master/content/advanced-topics/configuration-file-analysis/index.md)

**Tables in markdown**

![format_md](https://user-images.githubusercontent.com/29823086/96144074-c4f0c800-0ed1-11eb-9c14-37ff1a68de16.png)

**Tables in site** issue in rendering

![format_html](https://user-images.githubusercontent.com/29823086/96144161-dd60e280-0ed1-11eb-8a06-3ec3f27443d6.png)

**Comment by SankBad** [comment] 2020-10-15 14:40
@oindrillac @cfchase

**Comment by oindrillac** [comment] 2020-10-19 19:23
@cfchase I was able to reproduce this, here's the test build on my [github pages](https://oindrillac.github.io/operate-first.github.io/cfa/blog). Currently there are no table boundaries
- Link to my [fork](https://github.com/oindrillac/operate-first.github.io)
- Link to the remote [blog](https://github.com/oindrillac/configuration-files-analysis/blob/master/docs/blog.md)


I also tried with .md tables and grid tables instead of embedded html tables, they are not rendered as tables on the site as well.
How do you recommend we format the tables, so they are rendered well?

Also there is an issue with the links in References in this blog, similar to #31. Do you have any ideas on how to fix that?

**Comment by oindrillac** [comment] 2020-10-20 16:54
@SankBad please see [comment](https://github.com/operate-first/operate-first.github.io/issues/31#issuecomment-712991434) by @cfchase for fixing the formatting issue with references :slightly_smiling_face:

**Comment by SankBad** [comment] 2020-10-20 16:59
Great :+1: Thanks for letting me know.

**Comment by cfchase** [comment] 2020-10-20 22:16
__TLDR__: Use markdown table or use patternfly classes such as the [docs](https://www.patternfly.org/v4/components/table/html) so the styles get applied.
```markdown
| Correct Format | Incorrect format | Error Message |
|:-----|:------|:------|
| socket= '/var/lib/mysql/mysql.sock’ | socket=‘MySql’ | TypeError: Data type of key ‘log_file’ should be ‘filename or filepath+filename' but it’s given as 'filepath' |
```

```html
<table class="pf-c-table">
  <thead>
  <tr>
    <td>Correct Format </td>
    <td>Incorrect format</td>
    <td>Error Message </td>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>socket= '/var/lib/mysql/mysql.sock’</td>
    <td>socket=‘MySql’
</td>
    <td>TypeError: Data type of key ‘log_file’ should be ‘filename or filepath+filename' but it’s given as 'filepath'</td>
  </tr>
  </tbody>
</table>
```

__Long Explanation__:  
Looks like the html is rendering just fine, but the table styles aren't applied.  We've included the patternfly React components and CSS but they require classes on the html for style.  In this case, the above html with css classes should render the table with the appropriate styling.  Also, you probably wanted to use a `thead` and `tbody`.

```html
<table class="pf-c-table">
  <thead> <tr><td>... </thead>
  <tbody> <tr><td>... </tbody>
</table>
```

In addition, I just merged a [PR](https://github.com/operate-first/operate-first.github.io/pull/46) to add the class `pf-c-table` if you defined the table in normal markdown.  That's probably the easiest thing short term.
```markdown
| Correct Format | Incorrect format | Error Message |
|:-----|:------|:------|
| socket= '/var/lib/mysql/mysql.sock’ | socket=‘MySql’ | TypeError: Data type of key ‘log_file’ should be ‘filename or filepath+filename' but it’s given as 'filepath' |
```

If default patternfly styling isn't good enough, you're able to do a lot of things since we're using MDX to transform our docs.
https://www.gatsbyjs.com/docs/mdx/getting-started/
https://mdxjs.com/
This will allow you to do pretty much anything from [Patternfly](https://www.patternfly.org/) using either the html or React versions if you need something really advanced.

Long term, it should be easier.  I'm going to break out Patternfly from the project and use it in a Gatsby theme so no one authoring docs needs to use html or jsx and we can control exactly how the markdown gets generated.  I'll do so as part of https://github.com/operate-first/operate-first.github.io/issues/18

**Closed as completed by cfchase** 2020-10-20 22:16 UTC
