### ISSUE TITLE
Unable to view changes on github pages branch

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#62] opened 2020-11-02 18:12 UTC
I am unable to preview my changes on my fork's branch

* Here's my github fork [master](https://github.com/oindrillac/operate-first.github.io.git) and as i do `make gh-pages-fork` I am able to view my changes on gh pages [https://oindrillac.github.io/operate-first.github.io/operate-first/](https://oindrillac.github.io/operate-first.github.io/operate-first/).

* However, on my [branch](https://github.com/oindrillac/operate-first.github.io/tree/test) as I do `make gh-pages-branch`, I do not see my changes as I go to [https://oindrillac.github.io/operate-first.github.io/test/](https://oindrillac.github.io/operate-first.github.io/test/)

I am referring the instructions [here](https://github.com/oindrillac/operate-first.github.io#previewing-your-changes-on-github-pages). Am I missing some steps out?

cc: @tumido @cfchase

**Comment by tumido** [comment] 2020-11-04 13:53
You're not missing anything out. It seems there's a bug somewhere.

I think your branch preview didn't get previewed/committed to the `gh-branch` at all. When you execute the `make gh-pages-branch` it actually runs [this command](https://github.com/operate-first/operate-first.github.io/blob/724d7075bf8326e30804aaca126d1a8f7cd3dade/package.json#L18) behind the scenes (The key is the last command in that chain):

```sh
PATH_PREFIX=\"/operate-first.github.io/$(git branch --show-current)\" \
gatsby build --prefix-paths && \
gh-pages -d public -a -e $(git branch --show-current) -m 'Preview Fork: Manual build of a branch'  # This is the key
``` 

Looking at your [fork's `gh-pages` branch history](https://github.com/oindrillac/operate-first.github.io/tree/gh-pages), there's no commit with a message `"Preview Fork: Manual build of a branch"`, instead there's a suspicious `-m` folder. So. That means, the `gh-pages` outputted all the built data into there. This destination is determined by the [`-e` option](https://github.com/tschaub/gh-pages/blob/e363b144defe8e555f5a54251a6f7f1297c0e3f6/bin/gh-pages.js#L37). And that means, the `-m` is value to `-e` and if we look at our command, it means that the only case when such thing can happen is when `$(git branch --show-current) ` outputs nothing...

```sh
gh-pages -d public -a -e $(git branch --show-current) -m 'Preview Fork: Manual build of a branch'
# becomes
gh-pages -d public -a -e -m 'Preview Fork: Manual build of a branch'
```

:tada: This is the root cause. However I'm struggling on how to solve it. Would quoting it help? Maybe we can force it with a conditional... This is hard to solve, since [it works on my end](https://github.com/tumido/operate-first.github.io/commit/b522e9db456ace675495700ce3ce7dafd30914d9). 

Can you please help me out and tell me output of these commands:

```sh
git branch --show-current
make gh-pages-branch
```

Does it work if you put the `git branch` query into quotes?

```sh
sed -i '/deploy-branch/s/-e \(\$(git branch --show-current)\)/-e \\"\1\\"/' package.json
make gh-pages-branch
```

**Closed as completed** 2020-11-05 15:21 UTC
